apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftp.fullname" . }}
  labels:
    {{- include "ftp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ftp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ftp
      protocol: TCP
      name: ftp
  {{- range untilStep (.Values.ftp.passivePortMin | int) (.Values.ftp.passivePortMax | int) 1 }}
    - port: {{ . }}
      targetPort: pasv{{ . }}
      protocol: TCP
      name: pasv{{ . }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalTrafficPolicy: Local
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
