fullnameOverride: backups

image:
  repository: ghcr.io/fab-infra/backuptools
  tag: opensuse16-20260728-1847-563bf6e

podSecurityContext:
  runAsUser: 1100
  runAsGroup: 1100

backends:
  gcs:
    bucket: jediholo-net-backups
  s3:
    provider: OVH
    region: rbx
    bucket: jediholo-net-backups
  swift:
    container: backups

backups:
  files:
    backends: swift,gcs
    subdir: jka

schedules:
  files: "30 6 * * *"

volumes:
  data:
    hostPath:
      path: /home/jka
      type: DirectoryOrCreate
