fullnameOverride: activemq

image:
  repository: ghcr.io/fab-infra/activemq
  tag: 6.2-2026.08.02-24853a7

podSecurityContext:
  runAsUser: 1004
  runAsGroup: 1005

nodeSelector:
  server-role-web: "true"
  domain-jediholo-net: "true"

volumes:
  data:
    hostPath:
      path: /home/domains/jediholo.net/activemq/data
      type: DirectoryOrCreate
