apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpbb.fullname" . }}
  labels:
    {{- include "phpbb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "phpbb.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "phpbb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "phpbb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.env }}
          envFrom:
            - secretRef:
                name: {{ include "phpbb.fullname" . }}-env
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.volumes.files }}
            - mountPath: /srv/www/apps/phpbb/files
              name: files
          {{- end }}
          {{- if .Values.volumes.images }}
            - mountPath: /srv/www/apps/phpbb/images
              name: images
          {{- end }}
          {{- if .Values.volumes.store }}
            - mountPath: /srv/www/apps/phpbb/store
              name: store
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.volumes.files }}
        - name: files
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.volumes.images }}
        - name: images
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.volumes.store }}
        - name: store
          {{- toYaml . | nindent 10 }}
      {{- end }}
